-- August 21, 2015
-- Add current country question to questionare
INSERT INTO ag.survey_question (survey_question_id, question_shortname, american, british) VALUES
(146, 'COUNTRY', 'Current country of residence', 'Current country of residence');
INSERT INTO survey_question_response_type (survey_question_id, survey_response_type) VALUES (146, 'SINGLE');

-- Add to survey as question right before current zipcode
UPDATE ag.group_questions SET display_index = 9 WHERE survey_question_id = 115;
INSERT INTO ag.group_questions (survey_group, survey_question_id, display_index) VALUES (-1, 146, 8);

-- Attach answers to new question
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Unspecified', 0);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Afghanistan', 1);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Aland Islands', 2);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Albania', 3);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Algeria', 4);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'American Samoa', 5);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Andorra', 6);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Angola', 7);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Anguilla', 8);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Antarctica', 9);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Antigua and Barbuda', 10);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Argentina', 11);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Armenia', 12);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Aruba', 13);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Australia', 14);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Austria', 15);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Azerbaijan', 16);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Bahamas', 17);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Bahrain', 18);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Bangladesh', 19);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Barbados', 20);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Belarus', 21);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Belgium', 22);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Belize', 23);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Benin', 24);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Bermuda', 25);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Bhutan', 26);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Bolivia', 27);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Bosnia and Herzegovina', 28);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Botswana', 29);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Bouvet Island', 30);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Brazil', 31);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'British Indian Ocean Territory', 32);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Brunei Darussalam', 33);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Bulgaria', 34);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Burkina Faso', 35);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Burundi', 36);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Cambodia', 37);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Cameroon', 38);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Canada', 39);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Cape Verde', 40);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Cayman Islands', 41);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Central African Republic', 42);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Chad', 43);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Chile', 44);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'China', 45);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Christmas Island', 46);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Cocos (Keeling) Islands', 47);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Colombia', 48);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Comoros', 49);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Congo', 50);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Congo, The Democratic Republic of The', 51);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Cook Islands', 52);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Costa Rica', 53);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Cote D''ivoire', 54);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Croatia', 55);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Cuba', 56);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Cyprus', 57);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Czech Republic', 58);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Denmark', 59);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Djibouti', 60);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Dominica', 61);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Dominican Republic', 62);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Ecuador', 63);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Egypt', 64);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'El Salvador', 65);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Equatorial Guinea', 66);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Eritrea', 67);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Estonia', 68);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Ethiopia', 69);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Falkland Islands (Malvinas)', 70);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Faroe Islands', 71);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Fiji', 72);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Finland', 73);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'France', 74);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'French Guiana', 75);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'French Polynesia', 76);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'French Southern Territories', 77);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Gabon', 78);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Gambia', 79);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Georgia', 80);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Germany', 81);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Ghana', 82);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Gibraltar', 83);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Greece', 84);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Greenland', 85);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Grenada', 86);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Guadeloupe', 87);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Guam', 88);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Guatemala', 89);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Guernsey', 90);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Guinea', 91);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Guinea-bissau', 92);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Guyana', 93);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Haiti', 94);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Heard Island and Mcdonald Islands', 95);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Holy See (Vatican City State)', 96);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Honduras', 97);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Hong Kong', 98);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Hungary', 99);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Iceland', 100);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'India', 101);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Indonesia', 102);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Iran, Islamic Republic of', 103);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Iraq', 104);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Ireland', 105);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Isle of Man', 106);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Israel', 107);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Italy', 108);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Jamaica', 109);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Japan', 110);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Jersey', 111);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Jordan', 112);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Kazakhstan', 113);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Kenya', 114);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Kiribati', 115);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Korea, Democratic People''s Republic of', 116);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Korea, Republic of', 117);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Kuwait', 118);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Kyrgyzstan', 119);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Lao People''s Democratic Republic', 120);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Latvia', 121);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Lebanon', 122);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Lesotho', 123);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Liberia', 124);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Libyan Arab Jamahiriya', 125);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Liechtenstein', 126);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Lithuania', 127);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Luxembourg', 128);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Macao', 129);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Macedonia, The Former Yugoslav Republic of', 130);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Madagascar', 131);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Malawi', 132);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Malaysia', 133);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Maldives', 134);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Mali', 135);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Malta', 136);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Marshall Islands', 137);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Martinique', 138);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Mauritania', 139);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Mauritius', 140);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Mayotte', 141);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Mexico', 142);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Micronesia, Federated States of', 143);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Moldova, Republic of', 144);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Monaco', 145);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Mongolia', 146);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Montenegro', 147);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Montserrat', 148);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Morocco', 149);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Mozambique', 150);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Myanmar', 151);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Namibia', 152);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Nauru', 153);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Nepal', 154);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Netherlands', 155);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Netherlands Antilles', 156);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'New Caledonia', 157);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'New Zealand', 158);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Nicaragua', 159);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Niger', 160);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Nigeria', 161);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Niue', 162);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Norfolk Island', 163);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Northern Mariana Islands', 164);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Norway', 165);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Oman', 166);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Pakistan', 167);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Palau', 168);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Palestinian Territory, Occupied', 169);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Panama', 170);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Papua New Guinea', 171);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Paraguay', 172);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Peru', 173);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Philippines', 174);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Pitcairn', 175);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Poland', 176);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Portugal', 177);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Puerto Rico', 178);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Qatar', 179);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Reunion', 180);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Romania', 181);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Russian Federation', 182);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Rwanda', 183);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Saint Helena', 184);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Saint Kitts and Nevis', 185);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Saint Lucia', 186);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Saint Pierre and Miquelon', 187);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Saint Vincent and The Grenadines', 188);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Samoa', 189);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'San Marino', 190);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Sao Tome and Principe', 191);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Saudi Arabia', 192);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Senegal', 193);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Serbia', 194);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Seychelles', 195);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Sierra Leone', 196);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Singapore', 197);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Slovakia', 198);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Slovenia', 199);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Solomon Islands', 200);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Somalia', 201);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'South Africa', 202);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'South Georgia and The South Sandwich Islands', 203);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Spain', 204);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Sri Lanka', 205);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Sudan', 206);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Suriname', 207);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Svalbard and Jan Mayen', 208);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Swaziland', 209);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Sweden', 210);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Switzerland', 211);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Syrian Arab Republic', 212);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Taiwan, Province of China', 213);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Tajikistan', 214);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Tanzania, United Republic of', 215);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Thailand', 216);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Timor-leste', 217);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Togo', 218);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Tokelau', 219);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Tonga', 220);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Trinidad and Tobago', 221);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Tunisia', 222);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Turkey', 223);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Turkmenistan', 224);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Turks and Caicos Islands', 225);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Tuvalu', 226);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Uganda', 227);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Ukraine', 228);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'United Arab Emirates', 229);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'United Kingdom', 230);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'United States', 231);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'United States Minor Outlying Islands', 232);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Uruguay', 233);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Uzbekistan', 234);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Vanuatu', 235);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Venezuela', 236);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Viet Nam', 237);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Virgin Islands, British', 238);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Virgin Islands, U.S.', 239);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Wallis and Futuna', 240);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Western Sahara', 241);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Yemen', 242);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Zambia', 243);
INSERT INTO ag.survey_question_response (survey_question_id, response, display_index) VALUES (146, 'Zimbabwe', 244);

-- add country column to zipcode table
ALTER TABLE ag.zipcodes ADD COLUMN country varchar;
UPDATE ag.zipcodes SET country = 'United States' WHERE state IN ('AL','AK','AZ','AR','CA','CO','CT','DC','DE','FL','GA','HI','ID','IL','IN','IA','KS','KY','LA','ME','MD','MA','MI','MN','MS','MO','MT','NE','NV','NH','NJ','NM','NY','NC','ND','OH','OK','OR','PA','RI','SC','SD','TN','TX','UT','VT','VA','WA','WV','WI','WY');
UPDATE ag.zipcodes SET country = 'Canada' WHERE state IN ('AB','BC','MB','NB','NL','NS','NT','NU','ON','PE','QC','SK','YT');
-- Delete the rest so the table can repopulate correctly
DELETE FROM ag.zipcodes WHERE country IS NULL;
