language: python
python:
  - "2.7"
sudo: false
addons:
  postgresql: "9.5"
services:
  - redis-server
  - postgresql 
before_install:
  - redis-server --version
  - sudo mount -o remount,size=25% /var/ramfs
install:
  - pip install --upgrade pip
  - pip install mock nose>=0.10.1 pep8 flake8 coveralls
  - travis_retry pip install .
script:
  - export AG_CONFIG=`pwd`/ag_config.txt.example
  - ag make test
  - nosetests --with-doctest --with-coverage --cover-package amgut
  - flake8 amgut setup.py scripts
after_success:
  - coveralls
